"""
https://github.com/DrInfy/sharpy-sc2/blob/develop/sharpy/managers/unit_value.py
"""
from sc2.ids.unit_typeid import UnitTypeId

destructable_2x2 = {
    UnitTypeId.ROCKS2X2NONCONJOINED,
    UnitTypeId.DEBRIS2X2NONCONJOINED
}

destructable_4x4 = {
    UnitTypeId.DESTRUCTIBLECITYDEBRIS4X4,
    UnitTypeId.DESTRUCTIBLEDEBRIS4X4,
    UnitTypeId.DESTRUCTIBLEICE4X4,
    UnitTypeId.DESTRUCTIBLEROCK4X4,
    UnitTypeId.DESTRUCTIBLEROCKEX14X4,
}

destructable_4x2 = {
    UnitTypeId.DESTRUCTIBLECITYDEBRIS2X4HORIZONTAL,
    UnitTypeId.DESTRUCTIBLEICE2X4HORIZONTAL,
    UnitTypeId.DESTRUCTIBLEROCK2X4HORIZONTAL,
    UnitTypeId.DESTRUCTIBLEROCKEX12X4HORIZONTAL,
}

destructable_2x4 = {
    UnitTypeId.DESTRUCTIBLECITYDEBRIS2X4VERTICAL,
    UnitTypeId.DESTRUCTIBLEICE2X4VERTICAL,
    UnitTypeId.DESTRUCTIBLEROCK2X4VERTICAL,
    UnitTypeId.DESTRUCTIBLEROCKEX12X4VERTICAL,
}

destructable_6x2 = {
    UnitTypeId.DESTRUCTIBLECITYDEBRIS2X6HORIZONTAL,
    UnitTypeId.DESTRUCTIBLEICE2X6HORIZONTAL,
    UnitTypeId.DESTRUCTIBLEROCK2X6HORIZONTAL,
    UnitTypeId.DESTRUCTIBLEROCKEX12X6HORIZONTAL,
}

destructable_2x6 = {
    UnitTypeId.DESTRUCTIBLECITYDEBRIS2X6VERTICAL,
    UnitTypeId.DESTRUCTIBLEICE2X6VERTICAL,
    UnitTypeId.DESTRUCTIBLEROCK2X6VERTICAL,
    UnitTypeId.DESTRUCTIBLEROCKEX12X6VERTICAL,
}

destructable_4x12 = {
    UnitTypeId.DESTRUCTIBLEROCKEX1VERTICALHUGE,
    UnitTypeId.DESTRUCTIBLEICEVERTICALHUGE
}

destructable_12x4 = {
    UnitTypeId.DESTRUCTIBLEROCKEX1HORIZONTALHUGE,
    UnitTypeId.DESTRUCTIBLEICEHORIZONTALHUGE
}

destructable_6x6 = {
    UnitTypeId.DESTRUCTIBLECITYDEBRIS6X6,
    UnitTypeId.DESTRUCTIBLEDEBRIS6X6,
    UnitTypeId.DESTRUCTIBLEICE6X6,
    UnitTypeId.DESTRUCTIBLEROCK6X6,
    UnitTypeId.DESTRUCTIBLEROCKEX16X6,
}

destructable_BLUR = {
    UnitTypeId.DESTRUCTIBLECITYDEBRISHUGEDIAGONALBLUR,
    UnitTypeId.DESTRUCTIBLEDEBRISRAMPDIAGONALHUGEBLUR,
    UnitTypeId.DESTRUCTIBLEICEDIAGONALHUGEBLUR,
    UnitTypeId.DESTRUCTIBLEROCKEX1DIAGONALHUGEBLUR,
    UnitTypeId.DESTRUCTIBLERAMPDIAGONALHUGEBLUR,
}

destructable_ULBR = {
    UnitTypeId.DESTRUCTIBLECITYDEBRISHUGEDIAGONALULBR,
    UnitTypeId.DESTRUCTIBLEDEBRISRAMPDIAGONALHUGEULBR,
    UnitTypeId.DESTRUCTIBLEICEDIAGONALHUGEULBR,
    UnitTypeId.DESTRUCTIBLEROCKEX1DIAGONALHUGEULBR,
    UnitTypeId.DESTRUCTIBLERAMPDIAGONALHUGEULBR,
}